### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by braverynew** [waxdred/Binance-Trader-Bot#3]
I've run app after few hours, app hang not send notification to discord. Please help! I think something wrong with proxy or IP banned (I restart many time but it doesn't run, when I restart modem, it run about 1 hour and stuck :)). I changed time sleep from 3 to 120 but  still hang

Thanks

**Comment by ret3030** [comment]
Hi, braverynew have you resolved this issue? I got the bot working but the notifications in discord are not showing up. Any ideas? 
Thank you

**Comment by waxdred** [comment]
Hi,
Number of API Binance requests: If your application makes a high number of API requests to Binance, it could overload the server and cause high CPU usage, leading to the program hanging or becoming unresponsive. Consider optimizing your code to reduce the number of API requests or find alternative ways to fetch the required data more efficiently.

CORS and CPU usage: You mentioned that running the application with 1 or 2 CORS (Cross-Origin Resource Sharing) causes high CPU usage. This could potentially impact the performance and stability of your program. You may need to optimize your code or infrastructure to handle the load more effectively. Additionally, ensure that your application is utilizing multi-threading properly to distribute the workload efficiently across CPU cores.

Proxy or IP ban: It's possible that your IP address has been banned by Binance due to excessive requests or suspicious activity. Restarting your modem might temporarily resolve the issue as it assigns a new IP address, but if the underlying problem persists, you may need to investigate alternative solutions such as rotating proxies or contacting Binance support for assistance.
